version: "3"

services:
  node:
    container_name: corretora
    image: node:16
    restart: always
    user: node
    tty: true #`docker run -t`
    stdin_open: true #`docker run -i`
    command: bash
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
      - JWT_SECRET=jwtExempleSecret
  db:
    container_name: corretora_db
    image: mysql:8.0.21
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_ROOT_PASSWORD=password
